//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoOpp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class COLLEGE_DETAILS
    {
        [DisplayName("Type")]
        public string EST_TYPE { get; set; }
        [DisplayName("College Name")]
        public string EST_NAME { get; set; }
        [DisplayName("Email_id")]
        public string EMAIL_ID { get; set; }
        [DisplayName("Password")]
        public string PASSWORD { get; set; }
        [DisplayName("City")]
        public string CITY { get; set; }
        [DisplayName("Address")]
        public string ADDRESS { get; set; }
        [DisplayName("Pincode")]
        public Nullable<int> PINCODE { get; set; }
        [DisplayName("Est_id")]
        public int EST_ID { get; set; }
    }
}
