//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoOpp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class INTERVIEW_STATUS_CL
    {
        public int INTERVIEW_ID_CL { get; set; }
        public string STUD_NAME { get; set; }
        public string EMAIL_ID { get; set; }
        public Nullable<long> MOBILE { get; set; }
        public string DEPARTMENT { get; set; }
        public string YEAR { get; set; }
        public Nullable<decimal> CGPA { get; set; }
        public string APTITUDE_ROUND { get; set; }
        public string TECHNICAL_ROUND { get; set; }
        public string HR_ROUND { get; set; }
        public string APP_STATUS { get; set; }
        public Nullable<int> STUD_ID { get; set; }
        public Nullable<int> EST_ID_CY { get; set; }
        public Nullable<int> EST_ID_CL { get; set; }
        public Nullable<int> NOTIFY_ID_CL { get; set; }
        public Nullable<int> NOTIFY_ID_CY { get; set; }
        [DisplayName("Recruit ID")]
        public Nullable<int> RECRUIT_ID_CY { get; set; }
        public Nullable<int> INTERVIEW_ID_CY { get; set; }
    }
}
