//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoOpp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class RECRUIT_APP_STATUS_CY
    {
        [DisplayName("Notify id")]
        public int NOTIFY_ID_CY { get; set; }
        [DisplayName("Recrui id")]
        public Nullable<int> RECRUIT_ID { get; set; }
        [DisplayName("Position")]
        public string POSITION { get; set; }
        [DisplayName("Job Location")]
        public string JOB_LOCATION { get; set; }
        [DisplayName("Job Description")]
        public string JOB_DESC { get; set; }
        [DisplayName("Skills Required")]
        public string SKILLS_REQ { get; set; }
        [DisplayName("Required CGPA")]
        public Nullable<decimal> REQ_CGPA { get; set; }
        [DisplayName("Created Date")]
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        [DisplayName("College Name")]
        public string EST_NAME { get; set; }
        [DisplayName("App Status")]
        public string APP_STATUS { get; set; }
        [DisplayName("Status")]
        public string APPROVAL_STATUS { get; set; }
        [DisplayName("Est id_CY")]
        public Nullable<int> EST_ID_CY { get; set; }
        [DisplayName("Est id_CL")]
        public Nullable<int> EST_ID_CL { get; set; }
        [DisplayName("Notify id_CL")]
        public Nullable<int> NOTIFY_ID_CL { get; set; }
    }
}
