//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoOpp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_DETAILS
    {
        public int STUD_ID { get; set; }
        public string NAME { get; set; }
        public string EMAIL_ID { get; set; }
        public Nullable<long> MOBILE { get; set; }
        public string DEPARTMENT { get; set; }
        public string YEAR { get; set; }
        public Nullable<decimal> CGPA { get; set; }
    }
}
